### ISSUE TITLE
Crash before loading, VillagerConfig error

### ISSUE THREAD

**Issue by xenanthropy** [CyclopsMC/CyclopsCore#17] opened 2016-05-20 11:19 UTC
using Forge version 12.16.1.1900, and version 0.6.0 of cyclopscore, it crashes before loading minecraft, here is my log: http://pastebin.com/U8rUXiXM

Only mods tested are cyclopscore and evilcraft, I was contemplating putting this under Evilcraft since it involves that in the error, and also Evilcraft doesn't actually pre-load, but I didn't since the error starts with Cyclopscore.

**Comment by rubensworks** [comment] 2016-05-20 11:22
Try updating to Forge 12.16.1.1907. Apparently I forgot to add that as minimal requirement to CyclopsCore, which is why it starts loading.

**Comment by xenanthropy** [comment] 2016-05-20 20:12
Nope, same problem with 1907

**Comment by rubensworks** [comment] 2016-05-20 20:33
Could you send me the full forge log? Because I can't see any reason why this crash is occuring from the stacktrace only.

**Comment by xenanthropy** [comment] 2016-05-20 20:38
http://pastebin.com/vb6cCShH

**Comment by rubensworks** [comment] 2016-05-20 20:39
Thanks! I'll try to look into it over the weekend.

**Comment by xenanthropy** [comment] 2016-05-20 20:40
Thank you :) I'll wait to play minecraft until then, I can't go on without those Evilcraft tanks ;p

**Comment by rubensworks** [comment] 2016-05-20 20:42
You could always use an earlier version of the mod until then ;-) Unless that also crashes your game?

**Comment by xenanthropy** [comment] 2016-05-20 20:45
I'll definitely try that, since there's a couple of other releases for 1.9. I'll try now actually and see... It works! Cyclops 0.5.9 works with the newest version of Evilcraft.

**Comment by rubensworks** [comment] 2016-05-22 13:28
I have no idea what may be causing your crash. I can not reproduce it in any way.
It looks like your EvilCraft jar somehow is calling CyclopsCore code in the wrong way, even though my code calls it correctly.

I suggest you try out the new 1.9.4 versions (which will be released later today), and see if that magically fixes your problem.

**Comment by xenanthropy** [comment] 2016-05-22 20:15
Are the 1.9.4 versions compatible with just regular 1.9?

**Comment by rubensworks** [comment] 2016-05-22 20:18
@xenanthropy No, they aren't. Most mods who already were on 1.9 will probably update to 1.9.4 soon enough.

**Comment by rubensworks** [comment] 2016-08-08 19:23
Considering this resolved.

**Closed as completed by rubensworks** 2016-08-08 19:23 UTC
Labels: bug, mc-1.9, unreproducible
