### ISSUE TITLE
Froze while Joining the World

### ISSUE THREAD

**Issue by reddvilzz** [CyclopsMC/CyclopsCore#169] opened 2022-07-03 02:58 UTC
#### Issue type:

- :question: Question 
I'm getting a crash on joining the world, well actually not a crash just the game froze while the console says 

> The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

usually I can get this to work just by closing and reload the world again, but this time I tried doing it 4 times and it still give me crash and I can't join my world.
Reading at the [crash report](https://github.com/CyclopsMC/CyclopsCore/files/9033998/crash-2022-07-03_09.49.32-server.txt) mentioning both Lag Goggles and Cyclops Core.

Tried removing Lag Goggles and it just give me slightly different [crash reports](https://github.com/CyclopsMC/CyclopsCore/files/9034004/crash-2022-07-03_10.06.03-server.txt) this time mentioning Tick Central, Cyclops Core and Integrated Proxy

Removed both Lag Goggles and Tick Central and now the [report](https://github.com/CyclopsMC/CyclopsCore/files/9034021/crash-2022-07-03_10.24.08-server.txt) showing Cyclops Core and Integrated Proxy only.

I'm on 1.12.2 also.

____

#### Question:

Can I get a help on identifying what seems to cause the crash?

**Comment by rubensworks** [comment] 2022-07-03 02:58
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by Krutoy242** [comment] 2022-07-03 07:14
Have same issue.

Error happen in CyclopsCore class, but actual reason is most likely the **Integrated Proxy**.

I created an issue on their side https://github.com/shBLOCK/IntegratedProxy/issues/29

**Comment by reddvilzz** [comment] 2022-07-03 13:02
Oh right, I removed IntegratedProxy mod while adding back both LagGoggles and Tick Central and the world load just fine, I guess there is really something in IntegratedProxy that cause this.

**Comment by rubensworks** [comment] 2022-07-03 14:41
Great, thanks for finding the cause @Krutoy242!
Closing this issue here then.

**Closed as completed by rubensworks** 2022-07-03 14:41 UTC
Labels: question
