### ISSUE TITLE
NPE w/ Youtubers+ Mod

### ISSUE THREAD

**Issue by WenXin20** [CyclopsMC/CyclopsCore#39] opened 2017-01-11 18:53 UTC
Cyclops Core v0.9.0
Everlasting Abilities v1.2.4
Youtubers+ v1.10.4
Forge 2022
I get this crash while loading a new world.
[Crash Log](http://pastebin.com/RuKJKcZd)

**Comment by rubensworks** [comment] 2017-01-11 21:28
@WenXin20 Could you report this to the mod author of the Youtubers mod? This looks like an error on their end while writing capabilities to NBT.

**Comment by WenXin20** [comment] 2017-01-12 00:27
Sure, it's reported [here](https://minecraft.curseforge.com/projects/youtubers-mod) on their curseforge page in the chat.

**Comment by rubensworks** [comment] 2017-01-20 19:09
I'm closing this issue, as it's clearly being caused by the Youtubers mod.

@WenXin20 If the mod author ever answers to your comment and needs any help, be sure to let me know here.

**Closed as completed by rubensworks** 2017-01-20 19:09 UTC

**Comment by WenXin20** [comment] 2017-01-21 05:20
Alright, thanks. No reply to it yet though.
