### ISSUE TITLE
NoSuchMethodError Exception on Forge 1.14.4-28.1.0

### ISSUE THREAD

**Issue by man-im-unoriginal-af** [CyclopsMC/CyclopsCore#138] opened 2019-09-14 21:03 UTC
#### Issue type: Probably a typo.

- :bug: Bug

____

#### Short description:

Mod is incompatible with Forge 28.1.0 with the following error message that looks to be a coding typo:

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/15/19 4:49 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getPersistantData()Lnet/minecraft/nbt/CompoundNBT;
```
Full log will be attached.

#### Steps to reproduce the problem:

1. Install CyclopsCore to /mods
2. Launch Minecraft
3. Load a save game

#### Expected behaviour:

Game will freeze whilst Console Output already laying out the error

____

#### Versions:

- This mod: 1.5.0
- Minecraft: 1.14.4
- Forge: 28.1.0

#### Log file:
https://pastebin.com/79gH5YDz

**Comment by rubensworks** [comment] 2019-09-15 06:14
Duplicate of https://github.com/CyclopsMC/EverlastingAbilities/issues/129

**Closed as completed by rubensworks** 2019-09-15 06:14 UTC
