### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by 0dikpah** [CyclopsMC/CyclopsCore#55] opened 2017-06-29 11:22 UTC
Minecraft 1.2
Forge-1.12-14.21.1.2387
[crash-2017-06-29_13.17.27-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/1111810/crash-2017-06-29_13.17.27-client.txt)

**Comment by rubensworks** [comment] 2017-06-29 11:23
Please always check existing issues before reporting, duplicate of #53.

**Closed as completed by rubensworks** 2017-06-29 11:23 UTC
Labels: duplicate
