### ISSUE TITLE
Machine Reader crash

### ISSUE THREAD

**Issue by ScottDTA** [CyclopsMC/CyclopsCore#136] opened 2019-05-02 01:48 UTC
#### Issue type:

- :bug:  Crash on opening machine reader

____

#### Short description:

Machine Reader crash attached to squeezer

#### Steps to reproduce the problem:

place a machine reader on squeezer and try to open GUI.  Crash everytime

#### Expected behaviour:

GUI would open and allow normal interaction

____

#### Versions:

- This mod:  1.12.2-2.2.1
- Minecraft:  1.12.2
- Forge: 14.23.5.2815

#### Log file:

https://pastebin.com/nqBNYnim

**Comment by rubensworks** [comment] 2019-05-02 05:31
Duplicate of https://github.com/CyclopsMC/IntegratedDynamics/issues/722, which has been fixed in dev (release coming later this week).

**Closed as completed by rubensworks** 2019-05-02 05:31 UTC
Labels: duplicate
