### ISSUE TITLE
Add Evilcraft to McEternal and game crashes on start

### ISSUE THREAD

**Issue by Bifasaurus** [CyclopsMC/CyclopsCore#178] opened 2023-08-20 18:09 UTC
#### Issue type: Mod pack Crash

- :bug: Bug 

____

#### Short description:

Added Evilcraft (EvilCraft-1.12.2-0.10.78) to Mc Eternal and get a crash on load;
"net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EvilCraft-Compat (evilcraftcompat)
Caused by: java.lang.NoSuchMethodError: crazypants.enderio.base.recipe.Recipe.<init>(Lcrazypants/enderio/base/recipe/IRecipeInput;ILcrazypants/enderio/base/recipe/RecipeBonusType;[Lcrazypants/enderio/base/recipe/RecipeOutput;)V"

#### Steps to reproduce the problem:

1. Add EvilCraft-1.12.2-0.10.78 to MC Eternal 1.6.1 (GF must have EVIL..hmmmm)
[crash-2023-08-20_12.28.16-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/12388838/crash-2023-08-20_12.28.16-client.txt)

2. Get Crash.

#### Expected behaviour:

Crash on load
____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.78
- Minecraft: 1.12.2
- Forge: 14.23.5.2860

**Comment by rubensworks** [comment] 2023-08-20 18:09
Thanks for reporting!

**Comment by Bifasaurus** [comment] 2023-08-20 18:13
You are welcome!  The crash report will call out an older version of Evilcraft I tried.  Both this and the newest for 1.12.2 cause the crash.

**Comment by rubensworks** [comment] 2023-08-21 06:23
Duplicate of https://github.com/CyclopsMC/EvilCraft/issues/807

**Closed as completed by rubensworks** 2023-08-21 06:23 UTC
Labels: bug, mc-1.12

**Comment by Bifasaurus** [comment] 2023-08-23 02:54
Thanks for your help!!!
