### ISSUE TITLE
CyclopsCore 1.9 crash Forge ver. 12.16.0.1811

### ISSUE THREAD

**Issue by MCP105** [CyclopsMC/CyclopsCore#14] opened 2016-03-26 09:10 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MMFMLCorePlugin (MultiMine-1.9.jar)
  LoadingPlugin (RandomThings-MC1.9-3.6.8.1.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/26/16 5:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class cyano.basemetals.BaseMetals
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:172)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class cyano.basemetals.BaseMetals
    at cyano.basemetals.BaseMetals.preInit(BaseMetals.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:128)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 180794792 bytes (172 MB) / 307576832 bytes (293 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.0.1811 31 mods loaded, 31 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1811-1.9.jar) 
    UCH Forge{12.16.0.1811} [Minecraft Forge](forge-1.9-12.16.0.1811-1.9.jar) 
    UCH AutoSapling{1.3} [AutoSapling](AutoSapling 1.3 MC1.9.jar) 
    UCE basemetals{2.0.1} [Base Metals](BaseMetals_1.9-2.0.1.jar) 
    UCH betterbuilderswands{0.5.2} [Better Builder's Wands](BetterBuildersWands-0.5.2-1.9r91+efa64cc.jar) 
    UCH BiomesOPlenty{4.0.0} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.0.1969-universal.jar) 
    UCH buildingbrickscompatvanilla{1.9-1.4.4} [Building Bricks Vanilla Compat](BuildingBricks-1.9-1.4.4.jar) 
    UCE buildingbricks{1.9-1.4.4} [Building Bricks](BuildingBricks-1.9-1.4.4.jar) 
    UCH claybucket{1.0} [Clay Bucket](ClayBucket-1.9-1.0.jar) 
    UCE cyclopscore{0.5.3} [Cyclops Core](CyclopsCore-1.9-0.5.3.jar) 
    UCE colossalchests{1.3.3} [Colossal Chests](ColossalChests-1.9-1.3.3.jar) 
    UCH flatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks](flatcoloredblocks-mc1.9-v2.2.jar) 
    UCH gravestone{1.2.1} [Gravestone](Gravestone Mod 1.2.1.jar) 
    UCE itemscroller{0.2.1} [Item Scroller](itemscroller-1.9-0.2.1.jar) 
    UCH JEI{3.1.0.170} [Just Enough Items](jei_1.9-3.1.0.170.jar) 
    UCH journeymap{1.9-5.1.5b3} [JourneyMap](journeymap-1.9-5.1.5b3-fairplay.jar) 
    UCH lteleporters{1.1.1} [Lemon's Simple Teleporters](LemonsSimpleTeleporters-1.1.1.jar) 
    UCH ModNameTooltip{1.2.0} [Mod Name Tooltip](modnametooltip_1.9-1.2.0.jar) 
    UCH morefood{1.1g} [More Food](morefood-1.1g.jar) 
    UCH AS_MultiMine{1.5.2} [Multi Mine](MultiMine-1.9.jar) 
    UCH Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.2-4.jar) 
    UCH packingtape{0.5} [Packing Tape](Packing Tape-0.5.jar) 
    UCH planttech{1.3.0} [Planttech](planttech-1.3.0 - 1.9.jar) 
    UCH progressiveautomation{1.6.36} [Progressive Automation](ProgressiveAutomation-1.9-1.6.36.jar) 
    UCH Psi{beta-29} [Psi](Psi-beta-29.jar) 
    UCH randomthings{3.6.8.1} [Random Things](RandomThings-MC1.9-3.6.8.1.jar) 
    UCH AS_Ruins{15.7} [Ruins Spawning System](Ruins-1.9.jar) 
    UCH simplegrinder{1.122.A19} [Simple Grinder](SimpleGrinder-1.122.A19.jar) 
    UCH AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.9.jar) 
    UCH WIT{1.0.8} [WIT](WIT-1.9-1.0.8-22.jar) 
    Loaded coremods (and transformers): 
MMFMLCorePlugin (MultiMine-1.9.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (RandomThings-MC1.9-3.6.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.0.0' Renderer: 'GeForce 8200/PCI/SSE2/3DNOW!'

**Comment by rubensworks** [comment] 2016-03-26 09:35
Please don't just _dump_ your crash logs here. I have no context, so I don't know what you did to cause this crash.
I don't even see in what way CyclopsCore is related to this, as I only see `cyano.basemetals.BaseMetals` in the stack.

**Comment by liftoff** [comment] 2016-03-27 14:25
I am also having a crash on startup with Forge 1.9-12.16.0.1811. I did some debugging and it appears that CyclopseCore will always crash with `java.lang.IllegalAccessError` starting with version 1805 (1804 works).  So if you look at what changed between 1804 and 1805 I'm sure you'll be able to figure out what the problem is.

I have uploaded my entire crash log here: http://paste.ee/p/fyjeM

Let me know if you need more information.

**Comment by rubensworks** [comment] 2016-03-27 14:29
Seems to be related to #13, Forge is doing some refactoring it seems, so mods are bound to break during this period. I'll look into it soon.

**Comment by rubensworks** [comment] 2016-03-27 15:20
Fixed in b0df023adf291016e79a282a4ffe2c4d5c333547, release coming soon.

**Closed as completed by rubensworks** 2016-03-27 15:20 UTC
Labels: bug
