### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [CyclopsMC/CyclopsCore#45] opened 2017-04-07 15:02 UTC
It looks like there is a problem with your mod and IC 2 2.6.193-ex110

https://gist.github.com/vrork/276c90453af0b3c2cd6641f5f0f70988

**Comment by rubensworks** [comment] 2017-04-07 15:18
Thanks for reporting, but this is a duplicate of CyclopsMC/CommonCapabilities#5

**Closed as completed by rubensworks** 2017-04-07 15:18 UTC
