### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by UnNinja** [CyclopsMC/CyclopsCore#27] opened 2016-11-10 13:23 UTC
http://pastebin.com/4FMP1jPF
Doesn't happen every time. maybe about 1 in 4 times

**Comment by rubensworks** [comment] 2016-11-11 09:28
I'm not able to reproduce this with any of the Cyclops mods loaded on the lastest Forge version.
I suspect that you are using a mod that is somehow messing with class loading, which could result in such strange crashes.
It is very likely that such a crash will also occur in other mods when this mod is not loaded.

I suggest that you have a look at the mods you are using, and try removing them one by one to see which one causes the problem.

**Comment by rubensworks** [comment] 2017-01-29 13:11
Closing this because of non-reproducibility.

**Closed as completed by rubensworks** 2017-01-29 13:11 UTC
Labels: unreproducible
