### ISSUE TITLE
Crash w/ Industrialcraft 2

### ISSUE THREAD

**Issue by FnordMan** [CyclopsMC/CyclopsCore#47] opened 2017-04-19 15:38 UTC
Crashes with both release 188 (latest on curse) and 200. (latest from jenkins) Doesn't crash with release 144. (previous release before 188 on curse)
attached crash report below. 

[crash-2017-04-19_10.32.20-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/935736/crash-2017-04-19_10.32.20-client.txt)

**Comment by rubensworks** [comment] 2017-04-20 05:01
Duplicate of CyclopsMC/CommonCapabilities#5

**Closed as completed by rubensworks** 2017-04-20 05:01 UTC
