### ISSUE TITLE
Possible problem player can't join server.

### ISSUE THREAD

**Issue by duckeggpie** [CyclopsMC/CyclopsCore#78] opened 2017-10-04 16:15 UTC
Hi, was suggested on MC forum that I post this here. We are getting an issue where one player's game is crashing every time he tries to join the server. He will show up in game for a second then crash out. He is the only one out of 6 of us having issues and I'm stuck. We are all running the same mod versions too. Thanks in advance.

at org.cyclops.cyclopscore.init.ModBaseVersionable.needsUpdate(ModBaseVersionable.java:56)
at org.cyclops.cyclopscore.tracking.Versions.onTick(Versions.java:141)

[Full crash log](https://pastebin.com/aqJPJLWV)

**Comment by rubensworks** [comment] 2017-10-04 21:39
Duplicate of #76, will be fixed in next release.

**Closed as completed by rubensworks** 2017-10-04 21:39 UTC
Labels: duplicate
