### ISSUE TITLE
1.12-0.10.6 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/CyclopsCore#54] opened 2017-06-28 16:09 UTC
Notes:
     on startup

crash report:
https://gist.github.com/6ed7c15d9becc2b8fc86c174d736d7c8

fml server latest:
https://gist.github.com/0ab5e8d877f6ab3b85ed9b8190b32d01

possibly related: #53

**Comment by rubensworks** [comment] 2017-06-29 06:53
Yes, indeed duplicate of #53

**Closed as completed by rubensworks** 2017-06-29 06:53 UTC
Labels: duplicate
